-- database/migrations/007_seed_data.sql
-- Seed initial data (FAQ, auto_answer_rules, cron_jobs)

BEGIN;

-- ═══════════════════════════════════════════════════════════
--  SEED: bot_config.auto_answer_rules
-- ═══════════════════════════════════════════════════════════
INSERT INTO bot_config.auto_answer_rules (topic, auto_answer_enabled, escalate_to_human, escalation_message) VALUES
('honorarios', FALSE, TRUE, 'Vou conectar você com alguém da equipe para falar sobre valores! Um momento...'),
('documentos', TRUE, FALSE, NULL),
('prazos', TRUE, FALSE, NULL),
('urgencia_violencia', FALSE, TRUE, 'Situação de urgência detectada. Encaminhando para atendimento prioritário...');

DO $$ BEGIN
    RAISE NOTICE '✅ Seeded 4 auto_answer_rules';
END $$;

-- ═══════════════════════════════════════════════════════════
--  SEED: bot_config.cron_jobs
-- ═══════════════════════════════════════════════════════════
INSERT INTO bot_config.cron_jobs (id, name, frequency_seconds, enabled) VALUES
('follow-up-leads', 'Follow-up Leads Inativos', 43200, TRUE),  -- 12h
('document-reminders', 'Cobrar Documentos Faltantes', 86400, TRUE),  -- 24h
('lawapp-sync', 'Sincronizar com LawApp', 3600, TRUE),  -- 1h
('clean-old-sessions', 'Limpar Sessões Antigas', 604800, TRUE);  -- 7d

DO $$ BEGIN
    RAISE NOTICE '✅ Seeded 4 cron_jobs';
END $$;

-- ═══════════════════════════════════════════════════════════
--  SEED: knowledge.faq (initial FAQ entries)
-- ═══════════════════════════════════════════════════════════
-- Note: Embeddings will be generated by n8n workflow later
-- For now, insert NULL embeddings (will be updated in Phase 2)

INSERT INTO knowledge.faq (question, answer, category, keywords, embedding) VALUES
(
  'Quanto vocês cobram?',
  'Cobramos 30% dos valores atrasados + 30% de 12 parcelas vincendas + UADs (R$ 159,21 cada). Pode parcelar em até 40% do valor total.',
  'cobranca',
  ARRAY['quanto custa', 'honorários', 'valor', 'preço'],
  NULL
),
(
  'Quais documentos preciso enviar?',
  'Depende do tipo de caso! Para aposentadoria rural: RG, CPF, comprovante de residência, ITR, declaração do sindicato. Me conta qual seu caso que te falo exatamente.',
  'documentos',
  ARRAY['documentos', 'preciso enviar', 'quais papeis'],
  NULL
),
(
  'Quanto tempo demora?',
  'Processo administrativo no INSS: 60-90 dias. Se precisar entrar na justiça: 1-2 anos. Mas recebe retroativo desde o pedido!',
  'prazos',
  ARRAY['quanto tempo', 'demora', 'prazo'],
  NULL
),
(
  'Como funciona o pagamento?',
  'Você só paga quando receber! Honorários são descontados dos valores atrasados. Pode parcelar em até 10x de 40% do total.',
  'cobranca',
  ARRAY['pagamento', 'quando pago', 'forma de pagamento'],
  NULL
),
(
  'O que é UAD?',
  'UAD é a Unidade de Atualização de Débito, usada pra calcular honorários. Cada UAD vale R$ 159,21. O número de UADs depende da complexidade do caso.',
  'cobranca',
  ARRAY['uad', 'unidade', 'calculo'],
  NULL
);

DO $$ BEGIN
    RAISE NOTICE '✅ Seeded 5 FAQ entries (embeddings NULL, will be generated in Phase 2)';
END $$;

COMMIT;
