-- database/migrations/011_seed_data_idempotent.sql
-- Idempotent seed data (replaces 007_seed_data.sql)
-- FIXES: ON CONFLICT handling, business rules extraction, data validation, i18n support

BEGIN;

-- Set transaction isolation to REPEATABLE READ (prevents phantom reads during seed)
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- ═══════════════════════════════════════════════════════════
--  SEED: bot_config.business_rules
-- ═══════════════════════════════════════════════════════════
-- Extract magic numbers from FAQ answers into configuration
INSERT INTO bot_config.business_rules (rule_name, rule_value, rule_type, description) VALUES
    ('honorarios_atrasados_pct', '{"value": 30}', 'percentage', 'Percentual sobre valores atrasados'),
    ('honorarios_vincendas_pct', '{"value": 30}', 'percentage', 'Percentual sobre 12 parcelas vincendas'),
    ('uad_value_brl', '{"value": 159.21, "currency": "BRL"}', 'currency', 'Valor da Unidade de Atualização de Débito (UAD)'),
    ('parcelamento_max_parcelas', '{"value": 10}', 'integer', 'Máximo de parcelas para pagamento'),
    ('parcelamento_pct_total', '{"value": 40}', 'percentage', 'Percentual máximo do total para parcelamento'),
    ('prazo_inss_dias_min', '{"value": 60}', 'integer', 'Prazo mínimo processo INSS (dias)'),
    ('prazo_inss_dias_max', '{"value": 90}', 'integer', 'Prazo máximo processo INSS (dias)'),
    ('prazo_judicial_anos_min', '{"value": 1}', 'integer', 'Prazo mínimo processo judicial (anos)'),
    ('prazo_judicial_anos_max', '{"value": 2}', 'integer', 'Prazo máximo processo judicial (anos)')
ON CONFLICT (rule_name) DO UPDATE SET
    rule_value = EXCLUDED.rule_value,
    updated_at = NOW(),
    version = bot_config.business_rules.version + 1;

DO $$ BEGIN
    RAISE NOTICE '✅ Seeded 9 business_rules (idempotent)';
END $$;

-- ═══════════════════════════════════════════════════════════
--  SEED: bot_config.auto_answer_rules
-- ═══════════════════════════════════════════════════════════
INSERT INTO bot_config.auto_answer_rules (topic, auto_answer_enabled, escalate_to_human, escalation_message) VALUES
    ('honorarios', FALSE, TRUE, 'Vou conectar você com alguém da equipe para falar sobre valores! Um momento...'),
    ('documentos', TRUE, FALSE, NULL),
    ('prazos', TRUE, FALSE, NULL),
    ('urgencia_violencia', FALSE, TRUE, 'Situação de urgência detectada. Encaminhando para atendimento prioritário...'),
    ('geral', TRUE, FALSE, NULL),
    ('cobranca', FALSE, TRUE, 'Vou conectar você com nossa equipe financeira. Um momento...')
ON CONFLICT (topic) DO UPDATE SET
    auto_answer_enabled = EXCLUDED.auto_answer_enabled,
    escalate_to_human = EXCLUDED.escalate_to_human,
    escalation_message = EXCLUDED.escalation_message,
    updated_at = NOW(),
    version = bot_config.auto_answer_rules.version + 1;

DO $$ BEGIN
    RAISE NOTICE '✅ Seeded 6 auto_answer_rules (idempotent)';
END $$;

-- ═══════════════════════════════════════════════════════════
--  SEED: bot_config.cron_jobs
-- ═══════════════════════════════════════════════════════════
INSERT INTO bot_config.cron_jobs (
    id,
    name,
    frequency_seconds,
    enabled,
    next_run,
    max_concurrent_executions,
    backoff_strategy,
    max_retries
) VALUES
    ('follow-up-leads', 'Follow-up Leads Inativos', 43200, TRUE, NOW() + INTERVAL '12 hours', 1, 'exponential', 3),
    ('document-reminders', 'Cobrar Documentos Faltantes', 86400, TRUE, NOW() + INTERVAL '24 hours', 1, 'exponential', 3),
    ('lawapp-sync', 'Sincronizar com LawApp', 3600, TRUE, NOW() + INTERVAL '1 hour', 2, 'linear', 5),
    ('clean-old-sessions', 'Limpar Sessões Antigas', 604800, TRUE, NOW() + INTERVAL '7 days', 1, 'none', 0)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    frequency_seconds = EXCLUDED.frequency_seconds,
    enabled = EXCLUDED.enabled,
    max_concurrent_executions = EXCLUDED.max_concurrent_executions,
    backoff_strategy = EXCLUDED.backoff_strategy,
    max_retries = EXCLUDED.max_retries,
    updated_at = NOW(),
    version = bot_config.cron_jobs.version + 1;

DO $$ BEGIN
    RAISE NOTICE '✅ Seeded 4 cron_jobs (idempotent with next_run constraint satisfied)';
END $$;

-- ═══════════════════════════════════════════════════════════
--  SEED: knowledge.faq (initial FAQ entries)
-- ═══════════════════════════════════════════════════════════
-- Note: Embeddings will be generated by n8n workflow later
-- For now, insert NULL embeddings (will be updated in Phase 2)
-- Business rules now reference bot_config.business_rules instead of hardcoded values

-- Helper function to get business rule value
CREATE OR REPLACE FUNCTION get_business_rule(rule_name_param TEXT)
RETURNS TEXT AS $$
DECLARE
    rule_val JSONB;
BEGIN
    SELECT rule_value INTO rule_val
    FROM bot_config.business_rules
    WHERE rule_name = rule_name_param
    AND deleted_at IS NULL;

    RETURN rule_val->>'value';
END;
$$ LANGUAGE plpgsql;

INSERT INTO knowledge.faq (question, answer, category, keywords, embedding, language, is_primary) VALUES
(
    'Quanto vocês cobram?',
    format(
        'Cobramos %s%% dos valores atrasados + %s%% de 12 parcelas vincendas + UADs (R$ %s cada). Pode parcelar em até %s%% do valor total.',
        get_business_rule('honorarios_atrasados_pct'),
        get_business_rule('honorarios_vincendas_pct'),
        get_business_rule('uad_value_brl'),
        get_business_rule('parcelamento_pct_total')
    ),
    'cobranca',
    ARRAY['quanto custa', 'honorários', 'valor', 'preço'],
    NULL,
    'pt-BR',
    TRUE
),
(
    'Quais documentos preciso enviar?',
    'Depende do tipo de caso! Para aposentadoria rural: RG, CPF, comprovante de residência, ITR, declaração do sindicato. Me conta qual seu caso que te falo exatamente.',
    'documentos',
    ARRAY['documentos', 'preciso enviar', 'quais papeis'],
    NULL,
    'pt-BR',
    TRUE
),
(
    'Quanto tempo demora?',
    format(
        'Processo administrativo no INSS: %s-%s dias. Se precisar entrar na justiça: %s-%s anos. Mas recebe retroativo desde o pedido!',
        get_business_rule('prazo_inss_dias_min'),
        get_business_rule('prazo_inss_dias_max'),
        get_business_rule('prazo_judicial_anos_min'),
        get_business_rule('prazo_judicial_anos_max')
    ),
    'prazos',
    ARRAY['quanto tempo', 'demora', 'prazo'],
    NULL,
    'pt-BR',
    TRUE
),
(
    'Como funciona o pagamento?',
    format(
        'Você só paga quando receber! Honorários são descontados dos valores atrasados. Pode parcelar em até %sx de %s%% do total.',
        get_business_rule('parcelamento_max_parcelas'),
        get_business_rule('parcelamento_pct_total')
    ),
    'cobranca',
    ARRAY['pagamento', 'quando pago', 'forma de pagamento'],
    NULL,
    'pt-BR',
    TRUE
),
(
    'O que é UAD?',
    format(
        'UAD é a Unidade de Atualização de Débito, usada pra calcular honorários. Cada UAD vale R$ %s. O número de UADs depende da complexidade do caso.',
        get_business_rule('uad_value_brl')
    ),
    'cobranca',
    ARRAY['uad', 'unidade', 'calculo'],
    NULL,
    'pt-BR',
    TRUE
)
ON CONFLICT (id) DO UPDATE SET
    question = EXCLUDED.question,
    answer = EXCLUDED.answer,
    category = EXCLUDED.category,
    keywords = EXCLUDED.keywords,
    language = EXCLUDED.language,
    is_primary = EXCLUDED.is_primary,
    updated_at = NOW();

DO $$ BEGIN
    RAISE NOTICE '✅ Seeded 5 FAQ entries (idempotent, embeddings NULL, i18n-ready, business rules referenced)';
END $$;

-- Drop helper function (no longer needed)
DROP FUNCTION IF EXISTS get_business_rule(TEXT);

-- ═══════════════════════════════════════════════════════════
--  DATA INTEGRITY VALIDATION
-- ═══════════════════════════════════════════════════════════
DO $$
DECLARE
    total_rules INT;
    total_auto_rules INT;
    total_cron INT;
    total_faq INT;
    invalid_cron INT;
    faq_without_category INT;
BEGIN
    -- Count rows
    SELECT COUNT(*) INTO total_rules FROM bot_config.business_rules WHERE deleted_at IS NULL;
    SELECT COUNT(*) INTO total_auto_rules FROM bot_config.auto_answer_rules WHERE deleted_at IS NULL;
    SELECT COUNT(*) INTO total_cron FROM bot_config.cron_jobs WHERE deleted_at IS NULL;
    SELECT COUNT(*) INTO total_faq FROM knowledge.faq WHERE deleted_at IS NULL;

    -- Validate cron job frequencies are reasonable (not too frequent)
    SELECT COUNT(*) INTO invalid_cron
    FROM bot_config.cron_jobs
    WHERE frequency_seconds < 60 -- Less than 1 minute is suspicious
    AND deleted_at IS NULL;

    -- Validate FAQ categories reference valid topics
    SELECT COUNT(*) INTO faq_without_category
    FROM knowledge.faq
    WHERE category IS NULL
       OR category NOT IN (SELECT topic FROM bot_config.auto_answer_rules)
    AND deleted_at IS NULL;

    -- Report validation results
    RAISE NOTICE '📊 Data Integrity Validation:';
    RAISE NOTICE '   business_rules: %', total_rules;
    RAISE NOTICE '   auto_answer_rules: %', total_auto_rules;
    RAISE NOTICE '   cron_jobs: %', total_cron;
    RAISE NOTICE '   faq entries: %', total_faq;

    IF invalid_cron > 0 THEN
        RAISE WARNING '⚠️  % cron jobs have frequency < 60s (may cause resource exhaustion)', invalid_cron;
    ELSE
        RAISE NOTICE '   ✅ All cron job frequencies are reasonable';
    END IF;

    IF faq_without_category > 0 THEN
        RAISE WARNING '⚠️  % FAQ entries have invalid categories', faq_without_category;
    ELSE
        RAISE NOTICE '   ✅ All FAQ entries reference valid categories';
    END IF;

    -- Validate embeddings dimension (if any exist)
    IF total_faq > 0 THEN
        DECLARE
            wrong_dim INT;
        BEGIN
            SELECT COUNT(*) INTO wrong_dim
            FROM knowledge.faq
            WHERE embedding IS NOT NULL
            AND vector_dims(embedding) != 1536;

            IF wrong_dim > 0 THEN
                RAISE WARNING '⚠️  % FAQ entries have wrong embedding dimension (expected 1536)', wrong_dim;
            ELSE
                RAISE NOTICE '   ✅ All FAQ embeddings have correct dimension';
            END IF;
        END;
    END IF;
END $$;

-- Record migration in tracking table
INSERT INTO public.schema_migrations (version, description, success)
VALUES ('011_seed_data_idempotent', 'Idempotent seed data with business rules and validation', TRUE)
ON CONFLICT (version) DO NOTHING;

COMMIT;
